// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgvhvkusufpzgjlipdpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhndmh2a3VzdWZwemdqbGlwZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODQxNDYsImV4cCI6MjA2OTY2MDE0Nn0.H6oElXNC8pzgYuScrb3APDba8Q-8DOz6OmTkGK9VoA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});